<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK8pfqd2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK8pfqd2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK8pfqd2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK8pfqd2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerK8pfqd2\appDevDebugProjectContainer([
    'container.build_hash' => 'K8pfqd2',
    'container.build_id' => '24c16c68',
    'container.build_time' => 1554911581,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK8pfqd2');
